[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}](https://github.com/Ziinc/treq/releases/tag/{{ version }}) - {{ timestamp | date(format="%-d %B %Y") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
{%- if commit.remote.pr_number %}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.remote.pr_title | default(value=commit.message) | split(pat="\n") | first | trim | trim_start_matches(pat="feat: ") | trim_start_matches(pat="feature: ") | trim_start_matches(pat="fix: ") | trim_start_matches(pat="chore: ") | upper_first }} ([#{{ commit.remote.pr_number }}](https://github.com/Ziinc/treq/pull/{{ commit.remote.pr_number }}))
{%- endif %}
{%- endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = []
commit_parsers = [
  { message = "^(feat|feature)", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^docs", skip = true },
  { message = "^doc", skip = true },
  { message = "^refactor", skip = true },
  { message = "^chore", skip = true },
  { body = ".*security", group = "Security" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"

[remote.github]
owner = "Ziinc"
repo = "treq"
