// Command modules
pub mod agent_dispatch;
pub mod auto_update;
pub mod binary;
pub mod commits;
pub mod file_browser_review;
pub mod file_view;
pub mod file_watcher;
pub mod filesystem;
pub mod github;
pub mod pending_review;
pub mod pty_commands;
pub mod repo_config;
pub mod session;
pub mod settings;
pub mod stash;
pub mod workspace;

// Re-export all commands for convenient access
pub use agent_dispatch::*;
pub use auto_update::*;
pub use binary::*;
pub use commits::*;
pub use file_browser_review::*;
pub use file_view::*;
pub use file_watcher::*;
pub use filesystem::*;
pub use github::*;
pub use pending_review::*;
pub use pty_commands::*;
pub use repo_config::*;
pub use session::*;
pub use settings::*;
pub use stash::*;
pub use workspace::*;
