//! N-API test helpers used by Vitest. Command `invoke` is generated by
//! `#[tauri_test::setup]` in `lib.rs`.
//!
//! Several functions here are exported only via napi for consumption from
//! JS/TS test code and are not called from Rust, so clippy's dead_code lint
//! does not see their real callers.
#![allow(dead_code)]

use napi_derive::napi;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Mutex;

use crate::binary_paths;
use crate::commands::file_watcher::WatcherManager;
use crate::db::Database;
use crate::pty::PtyManager;
use crate::AppState;

use crate::e2e_test_helpers::TestRepo;

pub fn init_test_state() -> Result<AppState, String> {
  let db_path = std::env::var("TREQ_APP_DB_PATH")
    .map(PathBuf::from)
    .unwrap_or_else(|_| {
      std::env::temp_dir().join(format!("treq-tauri-test-{}.db", std::process::id()))
    });

  if let Some(parent) = db_path.parent() {
    std::env::set_var("TREQ_APP_DATA_DIR", parent.to_string_lossy().to_string());
    std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
  }
  std::env::set_var("TREQ_APP_DB_PATH", db_path.to_string_lossy().to_string());

  let db = Database::new(db_path).map_err(|e| format!("Failed to open database: {e}"))?;
  db.init()
    .map_err(|e| format!("Failed to initialize database: {e}"))?;

  let mut detected = HashMap::new();
  for binary in ["git", "jj", "claude", "codex", "cursor-agent", "copilot"] {
    if let Some(path) = binary_paths::detect_binary(binary) {
      detected.insert(binary.to_string(), path);
    }
  }
  binary_paths::init_binary_paths_cache(detected);

  let log_dir = std::env::temp_dir().join(format!("treq-tauri-test-logs-{}", std::process::id()));
  let telemetry = crate::telemetry::init(&log_dir).map_err(|e| e.to_string())?;

  Ok(AppState::new(
    db,
    PtyManager::new(),
    WatcherManager::new(),
    uuid::Uuid::new_v4().to_string(),
    0,
    String::new(),
    telemetry,
  ))
}

#[napi(object)]
pub struct TestRepoInfo {
  pub repo_path: String,
  pub temp_dir_path: String,
  pub default_branch: String,
}

static TEST_REPOS: Mutex<Vec<TestRepo>> = Mutex::new(Vec::new());

pub fn create_test_repo_impl(with_remote: bool) -> Result<TestRepoInfo, String> {
  let repo = crate::e2e_test_helpers::create_test_repo(with_remote)?;
  let info = TestRepoInfo {
    temp_dir_path: repo.temp_dir.path().to_string_lossy().to_string(),
    repo_path: repo.repo_path.clone(),
    default_branch: repo.default_branch().to_string(),
  };
  TEST_REPOS.lock().map_err(|e| e.to_string())?.push(repo);
  Ok(info)
}

pub fn cleanup_test_repo_impl(temp_dir_path: &str) -> Result<(), String> {
  let repo = {
    let mut repos = TEST_REPOS.lock().map_err(|e| e.to_string())?;
    repos
      .iter()
      .position(|repo| repo.temp_dir.path() == std::path::Path::new(temp_dir_path))
      .map(|position| repos.remove(position))
  };
  drop(repo);
  Ok(())
}

fn snapshot_working_copy(workspace_path: &str) {
  let _ = crate::jj::jj_get_changed_files(workspace_path);
}

#[napi]
pub fn create_test_repo(with_remote: bool) -> napi::Result<TestRepoInfo> {
  create_test_repo_impl(with_remote).map_err(napi::Error::from_reason)
}

#[napi]
pub fn cleanup_test_repo(temp_dir_path: String) -> napi::Result<()> {
  cleanup_test_repo_impl(&temp_dir_path).map_err(napi::Error::from_reason)
}

#[napi]
pub fn write_workspace_file(
  workspace_path: String,
  relative_path: String,
  content: String,
  append: Option<bool>,
) -> napi::Result<String> {
  crate::e2e_test_helpers::write_test_file(
    &workspace_path,
    &relative_path,
    &content,
    append.unwrap_or(false),
  )
  .map_err(napi::Error::from_reason)
}

#[napi]
pub fn write_repo_file(
  repo_path: String,
  relative_path: String,
  content: String,
  append: Option<bool>,
) -> napi::Result<String> {
  crate::e2e_test_helpers::write_test_file(
    &repo_path,
    &relative_path,
    &content,
    append.unwrap_or(false),
  )
  .map_err(napi::Error::from_reason)
}

#[napi]
pub fn git_commit_all(repo_path: String, message: String) -> napi::Result<()> {
  TestRepo::run_git(&repo_path, &["add", "."]).map_err(napi::Error::from_reason)?;
  TestRepo::run_git(&repo_path, &["commit", "-m", &message]).map_err(napi::Error::from_reason)?;
  Ok(())
}

#[napi]
pub fn resolve_commit_id(workspace_path: String, revision: String) -> napi::Result<String> {
  snapshot_working_copy(&workspace_path);
  crate::jj::jj_get_commit_id(&workspace_path, &revision)
    .map_err(|e| napi::Error::from_reason(e.to_string()))
}

#[napi]
pub fn resolve_change_id(workspace_path: String, revision: String) -> napi::Result<String> {
  snapshot_working_copy(&workspace_path);
  crate::jj::jj_get_change_id(&workspace_path, &revision)
    .map_err(|e| napi::Error::from_reason(e.to_string()))
}

#[napi]
pub fn resolve_revset_commit_ids(
  workspace_path: String,
  revset: String,
) -> napi::Result<Vec<String>> {
  snapshot_working_copy(&workspace_path);
  crate::jj::jj_log_revset_commit_ids(&workspace_path, &revset)
    .map_err(|e| napi::Error::from_reason(e.to_string()))
}

#[napi]
pub fn new_commit_with_parents(
  workspace_path: String,
  parent_revisions: Vec<String>,
) -> napi::Result<String> {
  snapshot_working_copy(&workspace_path);
  crate::jj::jj_new_with_parents(&workspace_path, &parent_revisions)
    .map_err(|e| napi::Error::from_reason(e.to_string()))
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn cleans_up_only_requested_test_repo() {
    let first = create_test_repo_impl(false).expect("create first test repo");
    let second = create_test_repo_impl(false).expect("create second test repo");

    cleanup_test_repo_impl(&first.temp_dir_path).expect("clean up first test repo");

    assert!(!std::path::Path::new(&first.temp_dir_path).exists());
    assert!(std::path::Path::new(&second.temp_dir_path).exists());

    cleanup_test_repo_impl(&second.temp_dir_path).expect("clean up second test repo");
  }
}
